= AsciiDoc 언어 문서

== AsciiDoc에 대하여

AsciiDoc은 주로 기술 문서 작성을 위해 설계된 경량의 의미론적 마크업 언어입니다. 이 언어는 간결하고 사람이 읽기 쉬운 일반 텍스트 형식으로 인코딩된 콘텐츠에서 다양한 프레젠테이션이 풍부한 출력 형식을 생성하는 데 사용될 수 있습니다.

AsciiDoc 구문은 텍스트를 마크업하고 구조화하기 위한 잘 확립된 일반 텍스트 규칙을 기반으로 하기 때문에 직관적입니다. AsciiDoc에 익숙하지 않은 사람도 구문 요소의 많은 부분을 보고 그 목적을 추측할 수 있을 것입니다. 이는 구문의 요소들이 의미하는 바와 비슷하게 보이도록 신중하게 선택되었기 때문입니다(기술 산업에서 오랫동안 사용해온 관행).

AsciiDoc 언어는 생성하는 출력 형식과 결합되어 있지 않습니다. AsciiDoc 프로세서는 AsciiDoc 소스 문서를 구문 분석하고 이해한 다음, 구문 분석된 문서 구조를 HTML, PDF, EPUB3, man(ual) 페이지 또는 DocBook과 같은 하나 이상의 출력 형식으로 변환할 수 있습니다. 여러 출력 형식을 생성할 수 있는 능력은 AsciiDoc의 주요 장점 중 하나입니다. 이 기능을 통해 정적 사이트 생성기, IDE, git 도구 및 서비스, CI/CD 시스템 및 기타 소프트웨어에서 사용될 수 있습니다.

AsciiDoc은 쉬운 작성과 기술 저작 및 출판의 엄격한 요구 사항 사이의 격차를 해소합니다. AsciiDoc은 읽거나 쓰는 데 텍스트 편집기만 필요하므로 시작하는 데 낮은 진입 장벽을 제공합니다.

== 이 문서에 대하여

여러분은 현재 Asciidoctor에서 구현된 AsciiDoc 언어에 대한 사용자 대상 문서를 읽고 있습니다. 이 문서는 AsciiDoc 콘텐츠를 처리하기 위해 Asciidoctor를 설정하고 사용하는 방법을 다루지 않습니다. 그런 문서는 이 웹사이트의 Asciidoctor 섹션에서 찾을 수 있습니다.

이 문서는 Eclipse의 AsciiDoc Language 프로젝트에 초기 기여로 제출되었습니다. 해당 프로젝트는 이 문서를 AsciiDoc 언어 사양 초안 작성의 기초로 사용할 것입니다. 또한 해당 프로젝트에서 유지 관리할 AsciiDoc Language의 사용자 대상 가이드의 초안으로도 사용될 것입니다.

AsciiDoc Language 사양의 첫 번째 버전이 비준될 때까지 AsciiDoc은 Asciidoctor 구현에 의해 정의됩니다. 언어에 대한 다른 공식적인 정의는 없습니다.

AsciiDoc 문서는 AsciiDoc Language 프로젝트가 자체 AsciiDoc Language 문서를 게시하기 시작할 때까지 이 사이트에 남아 있을 것입니다.

그때까지, 시작해 봅시다!